"""add_category_to_events

Revision ID: f06462ccbc55
Revises: add_group_members_table
Create Date: 2025-09-07 21:42:25.112820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f06462ccbc55'
down_revision: Union[str, Sequence[str], None] = 'add_group_members_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('category', sa.String(), nullable=True))
    op.alter_column('rsvps', 'status',
               existing_type=postgresql.ENUM('yes', 'no', 'maybe', name='rsvp_status'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rsvps', 'status',
               existing_type=postgresql.ENUM('yes', 'no', 'maybe', name='rsvp_status'),
               nullable=True)
    op.drop_column('events', 'category')
    # ### end Alembic commands ###
